import SmoothScroll from '@/components/common/SmoothScroll/SmoothScroll';
import Contact from '@/components/Contact';
import Description from '@/components/landing-page/Description';
import Hero from '@/components/landing-page/Hero';
import Projects from '@/components/landing-page/Projects';
import SlidingImages from '@/components/landing-page/SlidingImages';
import sanityClient from '@/utils/sanity/client';
import { WORK_QUERY } from '@/utils/sanity/queries';
import type { Project } from './work/page';

interface HomeProps {}

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

async function getPageData(): Promise<Project[]> {
  try {
    return await sanityClient.fetch(WORK_QUERY, { start: 0, end: 8 });
  } catch (error) {
    throw new Error(error as string);
  }
}

const Home: React.FC<HomeProps> = async () => {
  const projects = await getPageData();

  return (
    <SmoothScroll>
      <Hero />
      <Description />
      {!!projects?.length && (
        <>
          <Projects projects={projects} />
          <SlidingImages projects={projects} />
        </>
      )}
      <Contact />
    </SmoothScroll>
  );
};

export default Home;
