import Hero from '@/components/work-page/Hero';
import Projects from '@/components/work-page/Projects';
import sanityClient from '@/utils/sanity/client';
import { WORK_QUERY } from '@/utils/sanity/queries';
import { SanityImageObject } from '@sanity/image-url/lib/types/types';
import type { Slug } from 'sanity';
import Contact from '@/components/Contact';
import Page from '@/components/common/Page';

export interface Category {
  _id: string;
  title: string;
}

export interface Project {
  _id: string;
  agency: string;
  mainImage: SanityImageObject;
  categories: Category[];
  client?: string;
  selectedWorks?: boolean;
  slug: Slug;
  title: string;
}

export const metadata = {
  title: 'Work',
  description: 'Generated by create next app',
};

async function getPageData(): Promise<Project[]> {
  try {
    return await sanityClient.fetch(WORK_QUERY, { start: 0, end: 8 });
  } catch (error) {
    throw new Error(error as string);
  }
}

const Work: React.FC<{}> = async () => {
  const projects = await getPageData();

  return (
    <Page pageName="Work">
      <Hero />
      {!!projects?.length && <Projects projects={projects} />}
      <Contact />
    </Page>
  );
};

export default Work;
