import sanityClient from '@/utils/sanity/client';
import { WORK_SLUGS_QUERY } from '@/utils/sanity/queries';
import { SanityImageObject } from '@sanity/image-url/lib/types/types';
import { Project } from '../page';
import Hero from '@/components/work-detail-page/Hero/Hero';
import { PortableTextBlock } from 'next-sanity';
import { Slug } from 'sanity';
import { notFound } from 'next/navigation';
import Images from '@/components/work-detail-page/Images/Images';
import MoreWorks from '@/components/work-detail-page/MoreWorks/MoreWorks';
import Page from '@/components/common/Page';

interface WorkDetailProps {
  params: { slug: string };
}

export interface NextProject {
  _id: string;
  title: string;
  slug: Slug;
  mainImage: SanityImageObject;
}

export interface ProjectFull extends Project {
  _createdAt: string;
  _updatedAt: string;
  images: SanityImageObject[];
  body: PortableTextBlock[];
  previewURL?: Slug;
  nextProject: NextProject;
}

export async function generateMetadata({ params }: WorkDetailProps) {
  const metaData = await sanityClient.fetch(
    `*[_type == "project" && slug.current == "${params.slug}"][0]{
      title,
    }`,
  );

  return {
    title: metaData?.title,
    description: 'Generated by create next app',
  };
}

async function getPageData(slug: string): Promise<ProjectFull> {
  try {
    return await sanityClient.fetch(WORK_SLUGS_QUERY(slug));
  } catch (error) {
    throw new Error(error as string);
  }
}

const WorkDetail: React.FC<WorkDetailProps> = async ({ params }) => {
  const project = await getPageData(params.slug);
  if (!project) notFound();

  const {
    title,
    agency,
    client,
    categories,
    mainImage,
    previewURL,
    images,
    nextProject,
  } = project;

  return (
    <Page pageName={title}>
      <Hero
        title={title}
        client={client}
        agency={agency}
        categories={categories}
        mainImage={mainImage}
        previewURL={previewURL}
      />
      {!!images?.length && <Images images={images} />}
      <MoreWorks {...nextProject} />
    </Page>
  );
};

export default WorkDetail;
